version: '3.8'  # Specify the Docker Compose version

services:
  cords_opcua_client:
    image: cords-opcua-client
    container_name: cords_opcua_client
    command: python opc_ua_client.py --opcua_reference_id="ProdEnergyMeter1" 
    environment:
      - PYTHONUNBUFFERED=1  # Optional: Keeps logs from being buffered
      
      # OPC UA Configuration
      - OPC_SERVER_URL=opc.tcp://0.0.0.0:4840/freeopcua/server/  # Server URL for OPC UA
      - OPC_NAMESPACE_URI=http://example.org  # Namespace URI for OPC UA
      - OPC_NAMESPACE=OPCUA_SERVER  # Namespace index for OPC UA
      - OPC_SERVERNAME=CORDS_LDT_Server # Server name for OPC UA

      # Data Source Manager Configuration
      - DATA_SOURCE_MANAGER_HOST=${DATA_SOURCE_MANAGER_HOST}  # Host for Data Source Manager
      - DATA_SOURCE_MANAGER_PORT=${DATA_SOURCE_MANAGER_PORT}  # Port for Data Source Manager

    volumes:
      - .:/app  # Mount the current directory to /app in the container
    ports:
      - "6000:6000"  # Optional: Expose ports if needed (adjust or remove as required)

    networks:
      - cords_network