version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    ports:
      - "1883:1883"
    restart: unless-stopped


  cords_opcua_client_mqqt:
    image: 192.168.76.220:5000/cords-docker-images:cords_opcua_client_mqqt
    depends_on:
      - mosquitto
    environment:
      OPC_SERVER_URL: "opc.tcp://192.168.76.220:4840/freeopcua/server/"
      OPC_NAMESPACE_URI: "http://example.org"
      OPC_NAMESPACE: "OPCUA_SERVER"
      OPC_SERVERNAME: "CORDS_LDT_Server"
      OPCUA_REFERENCE_ID: "TestBedSmartMeter1"

      DATA_SOURCE_MANAGER_PORT: "32412"
      DATA_SOURCE_MANAGER_HOST: "192.168.76.220"
    restart: unless-stopped

