version: '3.8'

services:
  cords_opcua_client_mqqt:
    image: 192.168.76.220:5000/cords_opcua_client_mqqt:latest
    restart: unless-stopped
    volumes:
      - ./config:/app/config  # Mount local config directory to container (optional)
    environment:
      OPC_SERVER_URL: "opc.tcp://192.168.76.220:4840/freeopcua/server/"
      OPC_NAMESPACE_URI: "http://example.org"
      OPC_NAMESPACE: "OPCUA_SERVER"
      OPC_SERVERNAME: "CORDS_LDT_Server"
      OPCUA_REFERENCE_ID: "TestBedSmartMeter1"

      DATA_SOURCE_MANAGER_PORT: "32412"
      DATA_SOURCE_MANAGER_HOST: "192.168.76.220"
    # ports:
    #   - "1883:1883"   # MQTT broker port
    #   # - "4840:4840"   # OPC UA server port
    networks:
      - opcua-network

networks:
  opcua-network:
    driver: bridge
