# Application Configuration

mysql:
  host: 127.0.0.1
  port: 3306
  dbname: energymeters
  username: root
  password: admin

influx:
  host: 127.0.0.1
  port: 8086
  org: mtu
  token: JOC0TKLtbsC4_UJVl7ebtbtwmmaTG3HmN1SUASmz60PgVH9SA70ehzA4n01V9AlbC22W1UJ0tTDtd22Y-vFoPg==

api:
  port: 5000
  host: 127.0.0.1
logging:
  level: INFO
  file: app.log

