# Application Configuration

database:
  host: 127.0.0.1
  port: 3306
  dbname: energymeters
  username: root
  password: admin

influx:
  username: admin
  password: influxadmin

opc:
  serverurl: opc.tcp://0.0.0.0:4840/freeopcua/server/
  namespaceuri: http://example.org
  namespace: OPCUA_SERVER
  servername: CORDS_LDT_Server
  map: ./metadata/mapping.json

api:
  port: 5000
  host: 127.0.0.1

logging:
  level: INFO
  file: app.log

