version: '3'
services:
  web:
    image: flask-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    network_mode: host 
  # Add other services (e.g., database) if needed

  opc_server:
    image: opc_server
    ports:
      - "4840:4840"
    volumes:
      - .:/app
    network_mode: host 


    