# Application Configuration


opc:
  server_url: opc.tcp://0.0.0.0:4840/freeopcua/server/
  namespace_uri: http://example.org
  namespace: OPCUA_SERVER
  servername: CORDS_LDT_Server
  map: ./metadata/mapping.json

data_source_manager:
  port: 5000
  host: 127.0.0.1

logging:
  level: INFO
  file: app.log

